import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1 },
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 10 },
    progress: { height: 4 },
    scroll: { padding: 24 },
    stepContent: { gap: 16 },
    stepTitle: { marginBottom: 8, fontWeight: '900' },
    stepSubtitle: { marginBottom: 20 },
    stepSubtitleText: { fontWeight: '900' },
    input: { backgroundColor: 'transparent' },
    footer: {
        paddingHorizontal: 24,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: 'rgba(0,0,0,0.05)',
        flexDirection: 'row',
    },
    reqBlock: {
        backgroundColor: 'rgba(0,0,0,0.02)',
        padding: 16,
        borderRadius: 12,
        marginBottom: 10,
    },
    reqHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
    reqHeaderCompact: { marginBottom: 10 },
    switchWrap: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    reqTitle: { fontWeight: '900' },
    reqLabel: { fontWeight: '800' },
    reqHint: { marginBottom: 10 },
    summaryCard: {
        backgroundColor: 'rgba(124, 58, 237, 0.08)',
        padding: 16,
        borderRadius: 12,
        marginTop: 20,
        borderWidth: 1,
        borderColor: 'rgba(124, 58, 237, 0.2)',
    },
    creditUsageCard: {
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(124, 58, 237, 0.18)',
    },
    creditUsageTop: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    creditIconWrap: {
        width: 44,
        height: 44,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(124, 58, 237, 0.10)',
    },
    creditUsageCopy: {
        flex: 1,
    },
    creditRows: {
        marginTop: 14,
        borderTopWidth: 1,
        borderTopColor: 'rgba(0,0,0,0.06)',
        paddingTop: 12,
        gap: 10,
    },
    creditRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    creditRowFinal: {
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: 'rgba(0,0,0,0.06)',
    },
    creditRowLabel: {
        flex: 1,
        fontWeight: '800',
        opacity: 0.78,
    },
    creditRowValue: {
        fontWeight: '900',
        fontSize: 18,
    },
    creditDebit: {
        fontWeight: '900',
        fontSize: 16,
    },
});
