export const OCCUPATION_OPTIONS = [
  'Student',
  'Employed (Private)',
  'Employed (Government)',
  'Self-employed',
  'Freelancer',
  'Business owner',
  'Unemployed',
  'Homemaker',
  'Retired',
] as const;

export const JOB_TITLE_OPTIONS = [
  'Accountant',
  'Artist',
  'Banker',
  'Beautician',
  'Business owner',
  'Chef',
  'Consultant',
  'Content creator',
  'Customer service',
  'Designer',
  'Doctor',
  'Driver',
  'Engineer',
  'Entrepreneur',
  'Healthcare worker',
  'Hospitality',
  'IT / Software',
  'Lawyer',
  'Marketing',
  'Nurse',
  'Operations',
  'Project manager',
  'Sales',
  'Teacher',
  'Technician',
] as const;

export const QUALIFICATION_OPTIONS = [
  'High School',
  'Diploma',
  'Bachelor’s',
  'Master’s',
  'PhD',
  'Professional Certification',
] as const;

export const SEX_OPTIONS = ['Male', 'Female', 'Other'] as const;

export const IDEAL_DATE_OPTIONS = [
  'Dinner',
  'Coffee',
  'Brunch',
  'Cinema',
  'Live music',
  'Dancing',
  'Art gallery',
  'Museum',
  'Cooking together',
  'Picnic',
  'Beach day',
  'Swimming',
  'Hiking',
  'Gym or fitness',
  'Arcade games',
  'Bowling',
  'Karaoke',
  'Wine tasting',
  'Dessert date',
  'Road trip',
  'Bookstore',
  'Comedy show',
  'Rooftop drinks',
  'Cocktail bar',
  'Food market',
  'Street food',
  'Sushi date',
  'Pizza night',
  'Fine dining',
  'Tea date',
  'Ice cream walk',
  'Park walk',
  'Sunset walk',
  'City stroll',
  'Boat ride',
  'Spa day',
  'Pottery class',
  'Paint and sip',
  'Farmers market',
  'Mini golf',
  'Escape room',
  'Board games',
  'Trivia night',
  'Concert',
  'Theatre show',
  'Poetry night',
  'Festival',
  'Zoo or aquarium',
  'Theme park',
  'Cycling',
  'Tennis',
  'Yoga class',
  'Climbing',
  'Horse riding',
  'Stargazing',
  'Staycation',
  'Volunteer date',
] as const;

/** Religion options for profile and spec requirements. "Any" = no filter when used as spec requirement. */
export const RELIGION_OPTIONS = [
    'Any',
    'Christianity',
    'Muslim',
    'Buddhist',
    'Sikh',
    'Hindu',
    'Jewish',
    'Other',
] as const;
