<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AdminActivityController;
use App\Http\Controllers\AdminFinancialsController;
use App\Http\Controllers\AdminInviteController;
use App\Http\Controllers\AdminManagementController;
use App\Http\Controllers\AdminContactController;
use App\Http\Controllers\AdminMediaModerationController;
use App\Http\Controllers\AdminModerationCaseController;
use App\Http\Controllers\AdminModerationStrikeController;
use App\Http\Controllers\AdminProviderController;
use App\Http\Controllers\AdminRiskController;
use App\Http\Controllers\AdminSuccessStoryController;
use App\Http\Controllers\AdminUserController;
use App\Http\Controllers\AppVersionController;
use App\Http\Controllers\Api\CreditsController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BlockController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\DateVoucherController;
use App\Http\Controllers\MeController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\ModerationAppealController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProviderController;
use App\Http\Controllers\ProviderInviteController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\SpecController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\SuccessStoryController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::post('/send-otp', [AuthController::class, 'sendOtp']);
Route::post('/register', [AuthController::class, 'register']);
Route::post('/login', [AuthController::class, 'login']);
Route::post('/admin/login', [AdminController::class, 'login'])->middleware('throttle:5,1');
Route::post('/admin/login/verify-otp', [AdminController::class, 'verifyLoginOtp'])->middleware('throttle:10,1');
Route::get('/public/providers', [ProviderController::class, 'index']);
Route::get('/public/providers/{provider}', [ProviderController::class, 'show']);
Route::get('/public/success-stories', [SuccessStoryController::class, 'index']);
Route::get('/app-version', [AppVersionController::class, 'show']);
Route::post('/public/contact', [SupportController::class, 'publicContact'])->middleware('throttle:5,1');
Route::post('/provider-registrations', [ProviderController::class, 'registerInterest']);
Route::post('/provider-password/setup', [ProviderController::class, 'setupPassword']);
Route::get('/provider-invites/validate', [ProviderInviteController::class, 'showPublic']);
Route::get('/admin-invites/validate', [AdminInviteController::class, 'showPublic']);
Route::post('/admin-invites/send-otp', [AdminInviteController::class, 'sendOtp']);
Route::post('/admin-invites/register', [AdminInviteController::class, 'register']);

Route::middleware(['auth:sanctum', 'device.fingerprint'])->group(function () {
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::post('/account/pause', [AccountController::class, 'pause']);
    Route::post('/account/unpause', [AccountController::class, 'unpause']);
    Route::delete('/account', [AccountController::class, 'delete']);

    Route::get('/user', [MeController::class, 'show']);
    Route::get('/me/moderation', [ModerationAppealController::class, 'status']);
    Route::put('/profile', [ProfileController::class, 'update']);
    Route::get('/users/filter-options', [UserController::class, 'filterOptions']);
    Route::get('/users', [UserController::class, 'index']);
    Route::get('/users/{id}', [UserController::class, 'show']);

    Route::get('/providers', [ProviderController::class, 'index']);
    Route::get('/providers/{provider}/reviews', [ProviderController::class, 'reviews']);
    Route::get('/providers/{provider}', [ProviderController::class, 'show']);
    Route::get('/my-specs', [SpecController::class, 'mySpecs']);
    Route::get('/dates', [SpecController::class, 'myDates']);
    Route::post('/dates/{date}/follow-up', [SpecController::class, 'scheduleFollowUpDate']);
    Route::get('/date-vouchers', [DateVoucherController::class, 'index']);
    Route::post('/date-vouchers/preview', [DateVoucherController::class, 'preview']);
    Route::post('/date-vouchers', [DateVoucherController::class, 'store']);
    Route::get('/date-vouchers/{voucher}', [DateVoucherController::class, 'show']);
    Route::get('/chats', [ChatController::class, 'index']);
    Route::post('/providers/{provider}/chat', [ChatController::class, 'openProviderThread'])->middleware('account.active');
    Route::get('/chats/{thread}', [ChatController::class, 'show']);
    Route::get('/chats/{thread}/archives', [ChatController::class, 'archives']);
    Route::get('/chats/{thread}/archives/{archive}', [ChatController::class, 'archive']);
    Route::post('/chats/{thread}/messages', [ChatController::class, 'sendMessage'])->middleware('account.active');
    Route::post('/chats/{thread}/read', [ChatController::class, 'markRead']);
    Route::get('/blocks', [BlockController::class, 'index']);
    Route::post('/blocks', [BlockController::class, 'store']);
    Route::delete('/blocks/{user}', [BlockController::class, 'destroy']);
    Route::post('/reports', [ReportController::class, 'store'])->middleware('throttle:reports');
    Route::post('/moderation/appeals', [ModerationAppealController::class, 'store'])->middleware('throttle:moderation-appeals');
    Route::get('/review-prompts', [ReviewController::class, 'pending']);
    Route::get('/date-vouchers/{voucher}/review-context', [ReviewController::class, 'context']);
    Route::post('/date-vouchers/{voucher}/provider-review', [ReviewController::class, 'provider']);
    Route::post('/date-vouchers/{voucher}/partner-review', [ReviewController::class, 'partner']);
    Route::post('/date-vouchers/{voucher}/review-dismiss', [ReviewController::class, 'dismiss']);
    Route::get('/admin/reports', [ReportController::class, 'index']);
    Route::patch('/admin/reports/{report}', [ReportController::class, 'update']);
    Route::get('/admin/media-moderation', [AdminMediaModerationController::class, 'index']);
    Route::patch('/admin/media-moderation/{media}/approve', [AdminMediaModerationController::class, 'approve']);
    Route::get('/admin/moderation/cases', [AdminModerationCaseController::class, 'index']);
    Route::get('/admin/moderation/cases/{case}', [AdminModerationCaseController::class, 'show']);
    Route::patch('/admin/moderation/cases/{case}', [AdminModerationCaseController::class, 'update']);
    Route::post('/admin/moderation/cases/{case}/warning', [AdminModerationStrikeController::class, 'warning']);
    Route::post('/admin/moderation/cases/{case}/strike', [AdminModerationStrikeController::class, 'issue']);
    Route::post('/admin/moderation/cases/{case}/suspend', [AdminModerationStrikeController::class, 'suspend']);
    Route::post('/admin/moderation/cases/{case}/ban', [AdminModerationStrikeController::class, 'ban']);
    Route::post('/admin/moderation/strikes/{strike}/revoke', [AdminModerationStrikeController::class, 'revoke']);
    Route::get('/admin/moderation/appeals', [ModerationAppealController::class, 'adminIndex']);
    Route::patch('/admin/moderation/appeals/{appeal}', [ModerationAppealController::class, 'adminUpdate']);
    Route::get('/admin/me', [AdminController::class, 'me']);
    Route::get('/admin/dashboard', [AdminController::class, 'dashboard']);
    Route::get('/admin/activity', [AdminActivityController::class, 'index']);
    Route::get('/admin/financials/vouchers', [AdminFinancialsController::class, 'vouchers']);
    Route::get('/admin/financials/credits', [AdminFinancialsController::class, 'credits']);
    Route::get('/admin/risk/users', [AdminRiskController::class, 'users']);
    Route::get('/admin/risk/ip-events', [AdminRiskController::class, 'ipEvents']);
    Route::get('/admin/users/{user}/risk', [AdminRiskController::class, 'user']);
    Route::get('/admin/management/admins', [AdminManagementController::class, 'admins']);
    Route::get('/admin/management/permissions', [AdminManagementController::class, 'permissions']);
    Route::patch('/admin/management/admins/{admin}/access', [AdminManagementController::class, 'updateAccess']);
    Route::get('/admin/management/admin-invites', [AdminInviteController::class, 'index']);
    Route::post('/admin/management/admin-invites', [AdminInviteController::class, 'store']);
    Route::post('/admin/management/admin-invites/{invite}/approve', [AdminInviteController::class, 'approve']);
    Route::post('/admin/management/admin-invites/{invite}/revoke', [AdminInviteController::class, 'revoke']);
    Route::get('/admin/provider-invites', [ProviderInviteController::class, 'index']);
    Route::post('/admin/provider-invites', [ProviderInviteController::class, 'store']);
    Route::post('/admin/provider-invites/{invite}/revoke', [ProviderInviteController::class, 'revoke']);
    Route::get('/admin/contact', [AdminContactController::class, 'index']);
    Route::get('/admin/contact/{ticket}', [AdminContactController::class, 'show']);
    Route::post('/admin/contact/{ticket}/reply', [AdminContactController::class, 'reply']);
    Route::patch('/admin/contact/{ticket}', [AdminContactController::class, 'updateStatus']);
    Route::delete('/admin/contact/{ticket}', [AdminContactController::class, 'destroy']);
    Route::get('/admin/success-stories', [AdminSuccessStoryController::class, 'index']);
    Route::post('/admin/success-stories', [AdminSuccessStoryController::class, 'store']);
    Route::patch('/admin/success-stories/{story}', [AdminSuccessStoryController::class, 'update']);
    Route::delete('/admin/success-stories/{story}', [AdminSuccessStoryController::class, 'destroy']);
    Route::get('/admin/users', [AdminUserController::class, 'index']);
    Route::get('/admin/users/{user}', [AdminUserController::class, 'show']);
    Route::patch('/admin/users/{user}/pause', [AdminUserController::class, 'pause']);
    Route::patch('/admin/users/{user}/unpause', [AdminUserController::class, 'unpause']);
    Route::patch('/admin/users/{user}/ban', [AdminUserController::class, 'ban']);
    Route::patch('/admin/users/{user}/unban', [AdminUserController::class, 'unban']);
    Route::patch('/admin/users/{user}/note', [AdminUserController::class, 'updateNote']);
    Route::get('/admin/providers', [AdminController::class, 'providers']);
    Route::get('/admin/providers/{provider}', [AdminProviderController::class, 'show']);
    Route::patch('/admin/providers/{provider}/approve', [AdminProviderController::class, 'approve']);
    Route::patch('/admin/providers/{provider}/reject', [AdminProviderController::class, 'reject']);
    Route::patch('/admin/providers/{provider}/note', [AdminProviderController::class, 'updateNote']);
    Route::post('/admin/providers/{provider}/resend-setup-email', [AdminProviderController::class, 'resendSetupEmail']);
    Route::get('/support/tickets', [SupportController::class, 'index']);
    Route::post('/support/tickets', [SupportController::class, 'store']);
    Route::get('/support/tickets/{ticket}', [SupportController::class, 'show']);
    Route::post('/support/tickets/{ticket}/messages', [SupportController::class, 'sendMessage']);
    Route::post('/support/tickets/{ticket}/read', [SupportController::class, 'markRead']);
    Route::patch('/support/tickets/{ticket}', [SupportController::class, 'update']);
    Route::post('/specs/{id}/join', [SpecController::class, 'join'])->middleware('account.active');
    Route::post('/specs/{id}/applications/{applicationId}/approve', [SpecController::class, 'approveApplication'])->middleware('account.active');
    Route::post('/specs/{id}/applications/{applicationId}/reject', [SpecController::class, 'rejectApplication'])->middleware('account.active');
    Route::post('/specs/{id}/applications/{applicationId}/eliminate', [SpecController::class, 'eliminateApplication'])->middleware('account.active');
    Route::post('/specs/{id}/like', [SpecController::class, 'toggleLike'])->middleware('account.active');
    Route::post('/specs/{id}/match', [SpecController::class, 'createDate'])->middleware('account.active');
    Route::post('/specs/{id}/extend-search', [SpecController::class, 'extendSearch'])->middleware('account.active');
    Route::get('/media/upload-limits', [MediaController::class, 'uploadLimits']);
    Route::post('/media/upload', [MediaController::class, 'upload'])->middleware('account.active');
    Route::get('/media/{media}', [MediaController::class, 'show']);
    Route::get('/user/requests', [SpecController::class, 'pendingRequests']);
    Route::post('/specs', [SpecController::class, 'store'])->middleware('account.active');
    Route::apiResource('specs', SpecController::class)->except(['store']);

    Route::post('/specs/{id}/rounds', [SpecController::class, 'startRound'])->middleware('account.active');
    Route::post('/rounds/{roundId}/answer', [SpecController::class, 'submitAnswer'])->middleware('account.active');
    Route::post('/rounds/{roundId}/close', [SpecController::class, 'closeRound'])->middleware('account.active');
    Route::post('/rounds/{roundId}/eliminate/{userId}', [SpecController::class, 'eliminateUser'])->middleware('account.active');
    Route::post('/rounds/{roundId}/eliminate', [SpecController::class, 'eliminateUsers'])->middleware('account.active');
    Route::post('/rounds/{roundId}/nudge', [SpecController::class, 'nudgeUsers'])->middleware('account.active');
    Route::post('/rounds/{roundId}/update', [SpecController::class, 'updateRound'])->middleware('account.active');

    Route::get('/notifications', [NotificationController::class, 'index']);
    Route::post('/notifications/{notification}/read', [NotificationController::class, 'markRead']);
    Route::post('/user/push-token', [NotificationController::class, 'updatePushToken']);

    Route::get('/credits/products', [CreditsController::class, 'products']);
    Route::post('/credits/grant', [CreditsController::class, 'grant']);
    Route::get('/credits/transactions', [CreditsController::class, 'transactions']);

    Route::prefix('provider')->group(function () {
        Route::get('/dashboard', [ProviderController::class, 'getDashboard']);
        Route::get('/bookings', [DateVoucherController::class, 'providerBookings']);
        Route::post('/bookings/{voucher}/approve', [DateVoucherController::class, 'approve']);
        Route::post('/bookings/{voucher}/reject', [DateVoucherController::class, 'reject']);
        Route::post('/settings', [ProviderController::class, 'updateSettings']);
        Route::post('/scan-qr/preview', [DateVoucherController::class, 'scanPreview']);
        Route::post('/scan-qr', [ProviderController::class, 'scanQRCode']);
        Route::get('/categories', [ProviderController::class, 'getCategories']);
    });
});
