import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1 },
    scrollContent: {},
    topNav: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 8,
        marginBottom: 8,
    },
    backButton: {
        margin: 0,
    },
    screenTitle: {
        fontWeight: '800',
        fontSize: 20,
        letterSpacing: -0.5,
    },
    header: {
        alignItems: 'center',
        marginBottom: 32,
        paddingHorizontal: 16,
    },
    avatarContainer: {
        position: 'relative',
        marginBottom: 16,
    },
    editBadge: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        borderRadius: 20,
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
    },
    headerMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
    },
    nameText: {
        fontWeight: 'bold',
    },
    usernameText: {
        marginTop: 2,
        fontWeight: '700',
    },
    section: {
        marginHorizontal: 16,
        marginBottom: 20,
        padding: 20,
        borderRadius: 20,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.05)',
    },
    walletSection: {
        marginHorizontal: 16,
        marginBottom: 20,
        padding: 20,
        borderRadius: 20,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.05)',
    },
    walletHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    walletTopUp: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 999,
    },
    walletRow: {
        flexDirection: 'row',
        gap: 12,
    },
    walletCard: {
        flex: 1,
        borderRadius: 16,
        padding: 16,
        minHeight: 92,
        justifyContent: 'center',
    },
    walletCoinWrap: {
        width: 52,
        height: 52,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255,255,255,0.18)',
    },
    walletCoin: {
        width: 42,
        height: 42,
    },
    walletBalanceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    walletAmount: {
        color: '#FFFFFF',
        fontWeight: '900',
        fontSize: 34,
        lineHeight: 38,
        marginLeft: 'auto',
    },
    walletBalanceCopy: {
        flex: 1,
    },
    walletBalanceLabel: {
        color: '#FFFFFF',
        fontWeight: '900',
        fontSize: 16,
    },
    walletBalanceHint: {
        color: 'rgba(255,255,255,0.82)',
        fontWeight: '700',
        fontSize: 12,
        marginTop: 2,
        lineHeight: 16,
    },
    sectionTitle: {
        marginBottom: 20,
        fontWeight: '800',
        textTransform: 'uppercase',
        fontSize: 11,
        letterSpacing: 1.2,
    },
    input: {
        backgroundColor: 'transparent',
        paddingHorizontal: 0,
    },
    inputContent: {
        paddingHorizontal: 0,
    },
    divider: {
        marginVertical: 8,
        opacity: 0.3,
    },
    rowInput: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 8,
    },
    rowBetween: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
    },
    lifestyleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        flexWrap: 'wrap',
    },
    lifestyleLabel: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        flex: 1,
        minWidth: 140,
    },
    lifestyleLabelText: {
        fontWeight: '600',
    },
    lifestylePills: {
        flexGrow: 1,
        minWidth: 200,
    },
    saveButton: {
        marginHorizontal: 16,
        marginTop: 8,
        marginBottom: 8,
        borderRadius: 16,
        elevation: 2,
    },
});
