import { Dimensions, StyleSheet } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const GALLERY_ITEM_SIZE = 72;
const GALLERY_GAP = 8;
const DASHBOARD_CARD_GAP = 8;
const DASHBOARD_CARD_WIDTH = Math.floor((SCREEN_WIDTH - 40 - DASHBOARD_CARD_GAP * 2) / 3);

export const providerDashboardStyles = StyleSheet.create({
  container: { flex: 1 },
  centered: { justifyContent: 'center', alignItems: 'center' },
  scroll: { flex: 1 },
  content: { paddingTop: 16 },
});

export const sectionStyles = StyleSheet.create({
  title: { fontSize: 16, fontWeight: '800', marginTop: 20, marginBottom: 8 },
});

export const styles = StyleSheet.create({
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 16,
    paddingBottom: 14,
  },
  topBarTitleWrap: { flex: 1 },
  topBarTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
  },
  headerIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  headerBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    overflow: 'hidden',
    backgroundColor: '#EF4444',
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 18,
  },
  mainImageWrap: { position: 'relative', width: SCREEN_WIDTH },
  mainImage: {
    width: SCREEN_WIDTH,
    height: 220,
    backgroundColor: '#e0e0e0',
  },
  mainImagePlaceholder: {
    width: SCREEN_WIDTH,
    height: 220,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  placeholderLabel: { fontSize: 14, fontWeight: '600' },
  editPhotoBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.8)',
    zIndex: 5,
    elevation: 5,
  },
  visitWebsiteOverlay: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 24,
    backgroundColor: 'rgba(0,0,0,0.65)',
  },
  visitWebsiteText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  dashboardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: DASHBOARD_CARD_GAP,
    marginBottom: 10,
  },
  dashboardCard: {
    width: DASHBOARD_CARD_WIDTH,
    minHeight: 92,
    borderRadius: 14,
    padding: 10,
    justifyContent: 'space-between',
  },
  dashboardIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashboardValue: { fontSize: 15, fontWeight: '800', marginTop: 8 },
  dashboardTitle: { fontSize: 11, fontWeight: '700', marginTop: 1 },
  dashboardHelper: { fontSize: 10, marginTop: 1 },
  galleryStrip: {
    flexDirection: 'row',
    gap: GALLERY_GAP,
    paddingBottom: 8,
  },
  galleryItemWrap: { borderRadius: 10, overflow: 'hidden' },
  galleryItem: {
    width: GALLERY_ITEM_SIZE,
    height: GALLERY_ITEM_SIZE,
    borderRadius: 10,
    backgroundColor: '#eee',
  },
  galleryAddItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  galleryEditBadge: {
    position: 'absolute',
    right: 4,
    bottom: 4,
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.8)',
    zIndex: 2,
  },
  galleryPlaceholder: {
    width: GALLERY_ITEM_SIZE,
    height: GALLERY_ITEM_SIZE,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  galleryPlaceholderText: { fontSize: 11 },
  input: { marginBottom: 8 },
  inputHalf: { flex: 1 },
  rowInputs: { flexDirection: 'row', gap: 10 },
  bodyText: { fontSize: 15, lineHeight: 22 },
  inlineSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inlineEditButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.18,
    shadowRadius: 2,
  },
  addressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 14,
    borderRadius: 12,
  },
  addressText: { fontSize: 15, flex: 1 },
  voucherCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
  },
  voucherBody: { flex: 1 },
  voucherTitle: { fontSize: 16, fontWeight: '800', marginBottom: 4 },
  voucherDesc: { fontSize: 14, lineHeight: 20 },
  bookingTermsCard: {
    gap: 12,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
  },
  termsRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  switchRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  switchCopy: { flex: 1 },
  switchTitle: { fontSize: 15, fontWeight: '800' },
  switchText: { fontSize: 13, lineHeight: 18, marginTop: 2 },
  yesNoToggle: {
    flexDirection: 'row',
    padding: 3,
    borderRadius: 999,
    backgroundColor: '#F3F0FA',
  },
  yesNoOption: {
    minWidth: 42,
    alignItems: 'center',
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 999,
  },
  yesNoText: { fontSize: 12, fontWeight: '800' },
  ratingPill: {
    position: 'absolute',
    top: 180,
    left: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  ratingText: { color: '#fff', fontSize: 14, fontWeight: '800' },
  saveBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    gap: 10,
    paddingTop: 12,
    paddingHorizontal: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#E7DDFB',
  },
  saveBarButton: { flex: 1 },
});
